#file: noinspection SpellCheckingInspection,ComposeUnknownValues,ComposeUnknownKeys

name: servicebus

services:
  sqledge:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'StrongPassword1234!'
    healthcheck:
      test: '/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$${MSSQL_SA_PASSWORD}" -Q "SELECT 1" -b -o /dev/null'
      interval: 10s
      timeout: 3s
      retries: 5
      start_interval: 5s

  # servicebus:
  #   image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
  #   volumes:
  #     - './Config.json:/ServiceBus_Emulator/ConfigFiles/Config.json:ro'
  #   ports:
  #     - '5672:5672/tcp'
  #     - '5300:5300/tcp'
  #   depends_on:
  #     sqledge:
  #       condition: service_healthy
  #   environment:
  #     SQL_SERVER: 'sqledge'
  #     ACCEPT_EULA: 'Y'
  #     SQL_WAIT_INTERVAL: '1'
  #     MSSQL_SA_PASSWORD: 'StrongPassword1234!'

  servicebus-healthcheck:
    build:
      context: ../ServiceBusEmulator.Healthcheck
      dockerfile: Dockerfile
    volumes:
      - './Config.json:/ServiceBus_Emulator/ConfigFiles/Config.json:ro'
    ports:
      - '5672:5672/tcp'
      - '5300:5300/tcp'
    depends_on:
      sqledge:
        condition: service_healthy
    environment:
      SQL_SERVER: 'sqledge'
      ACCEPT_EULA: 'Y'
      SQL_WAIT_INTERVAL: '1'
      MSSQL_SA_PASSWORD: 'StrongPassword1234!'
    healthcheck:
      test: ['CMD', '/ServiceBusEmulator.Healthcheck']
      interval: 10s
      timeout: 3s
      retries: 5
      start_interval: 5s
      